"""Add is_admin and enforce single admin

Revision ID: 4211e797877d
Revises: 7175fad83765
Create Date: 2025-12-11 14:41:47.960728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4211e797877d'
down_revision: Union[str, Sequence[str], None] = '7175fad83765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###

    # Partial uniqueness - only one admin, other records can be false
    op.create_index(
    'unique_admin_only_one',
    'users',
    ['is_admin'],
    unique=True,
    postgresql_where=sa.text("is_admin = TRUE")
)



def downgrade() -> None:
    """Downgrade schema."""
    # Drop uniqueness
    op.drop_index('unique_admin_only_one', table_name='users')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
